name: kubico
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  alphabet_list_scroll_view: ^2.0.0
  another_flushbar: ^1.12.30
  brasil_fields: ^1.1.4
  cached_network_image: ^3.1.0
  carousel_pro_nullsafety: ^2.0.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.11.0
  cloud_functions: ^4.5.1
  credit_card_type_detector: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  firebase_storage: ^11.3.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^9.1.0
  geocode: ^1.0.1
  geolocator: ^10.0.1
  get: ^4.3.8
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  image_cropper: ^4.0.1
  image_picker: ^1.0.4
  keyboard_actions: ^4.2.0
  map_launcher: ^3.0.1
  provider: ^6.0.0
  rflutter_alert: ^2.0.4
  url_launcher: ^6.0.12
  uuid: ^4.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  linter: ^1.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo512x512.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/fenix.png
    - images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Thin.otf
          weight: 100
          style: normal
        - asset: fonts/Metropolis-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/Metropolis-ExtraLight.otf
          weight: 200
          style: normal
        - asset: fonts/Metropolis-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/Metropolis-Light.otf
          weight: 300
          style: normal
        - asset: fonts/Metropolis-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/Metropolis-Regular.otf
          weight: 400
          style: normal
        - asset: fonts/Metropolis-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/Metropolis-Medium.otf
          weight: 500
          style: normal
        - asset: fonts/Metropolis-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Metropolis-SemiBold.otf
          weight: 600
          style: normal
        - asset: fonts/Metropolis-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Metropolis-Bold.otf
          weight: 700
          style: normal
        - asset: fonts/Metropolis-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Metropolis-ExtraBold.otf
          weight: 800
          style: normal
        - asset: fonts/Metropolis-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Metropolis-Black.otf
          weight: 900
          style: normal
        - asset: fonts/Metropolis-BlackItalic.otf
          weight: 900
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
